config/routes.rb
Rails.application.routes.draw do
  resources :conversations
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "conversations#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/conversation.rb
class Conversation < ApplicationRecord

  has_many :responses


  def broadcast_hello
    ConversationChannel.broadcast_to(self, { message: "Hello from #{title}" })
  end

  def broadcast_response(response_record)
    ConversationChannel.broadcast_to(self, response_record.as_json)
  end
end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :conversation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :set_conversation, only: %i[ show edit update destroy ]

  # GET /conversations or /conversations.json
  def index
    @conversations = Conversation.all
  end

  # GET /conversations/1 or /conversations/1.json
  def show
  end

  # GET /conversations/new
  def new
    @conversation = Conversation.new
  end

  # GET /conversations/1/edit
  def edit
  end

  # POST /conversations or /conversations.json
  def create
    @conversation = Conversation.new(conversation_params)

    respond_to do |format|
      if @conversation.save
        format.html { redirect_to conversation_url(@conversation), notice: "Conversation was successfully created." }
        format.json { render :show, status: :created, location: @conversation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conversations/1 or /conversations/1.json
  def update
    respond_to do |format|
      if @conversation.update(conversation_params)
        format.html { redirect_to conversation_url(@conversation), notice: "Conversation was successfully updated." }
        format.json { render :show, status: :ok, location: @conversation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conversations/1 or /conversations/1.json
  def destroy
    @conversation.destroy!

    respond_to do |format|
      format.html { redirect_to conversations_url, notice: "Conversation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conversation
      @conversation = Conversation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def conversation_params
      params.require(:conversation).permit(:title, :subject)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.haml
%div{:id => "#{dom_id conversation}"}
  %p
    %strong Title:
    = conversation.title
  %p
    %strong Subject:
    = conversation.subject

app/views/conversations/_form.html.haml
= form_with(model: conversation) do |form|
  - if conversation.errors.any?
    .alert.alert-danger
      %h2
        = pluralize(conversation.errors.count, 'error')
        prohibited this conversation from being saved:
      %ul
        - conversation.errors.each do |error|
          %li= error.full_message
  .mb-3
    = form.label :title, class: 'form-label'
    = form.text_field :title, class: 'form-control'
  .mb-3
    = form.label :subject, class: 'form-label'
    = form.text_field :subject, class: 'form-control'
  .mb-3
    = form.submit class: 'btn btn-primary'

app/views/conversations/edit.html.haml
%h1 Editing conversation
= render "form", conversation: @conversation
%br/
%div
  = link_to "Show this conversation", @conversation
  |
  \#{link_to "Back to conversations", conversations_path}

app/views/conversations/index.html.haml
%p= notice
%h1 Conversations
%p= link_to 'New conversation', new_conversation_path, class: 'btn btn-primary'

#conversations
  - @conversations.each do |conversation|
    = render conversation
    %p
      = link_to 'Show this conversation', conversation

app/views/conversations/new.html.haml
.row
  .col
    %h1 New conversation
    = render "form", conversation: @conversation
    %br/
    %div
      = link_to "Back to conversations", conversations_path
  .col

app/views/conversations/show.html.haml
%p{:style => "color: green"}= notice

.row
  .col-md-12.mt-3
    = render @conversation

.row
  .col-md-12.mt-3{ 'data-controller' => 'conversation', 'data-conversation-id-value' => @conversation.id }
.row
  .col-md-12.mt-3
    = link_to 'Back to conversations', conversations_path

.row
  .col-md-12.mt-3
    #messages

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TwoLlms
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    .container
      .row
        .col-md-12= yield